/**
 * 翻译字典模块
 * 
 * safeGlobalDict:  安全长句字典，不会与代码变量冲突，可直接全局替换
 * riskyShortWords: 危险短词字典，只能在 UI 属性上下文中替换，否则会导致白屏
 */

const safeGlobalDict = {
    "Manage Account": "管理账号",
    "Manage your account and billing": "管理您的账号与账单",
    "Invite Team Members": "邀请团队成员",
    "Accelerate development, shared knowledge, and context across your team": "跨团队加速开发并共享知识与上下文",
    "Preferences": "偏好设置",
    "Cursor Account": "Cursor 账号",
    "Warning Notifications": "警告通知",
    "Show warning-level in-app toasts": "显示警告级别的应用内提示",
    "Menu Bar Icon": "菜单栏图标",
    "Show Cursor in menu bar": "在菜单栏显示 Cursor",
    "Worktrees": "工作树",
    "Cleanup": "清理",
    "Cursor periodically removes old worktrees to free disk space. Tune how aggressively cleanup runs.": "Cursor 会定期移除旧工作树以释放磁盘空间。可调整清理执行的积极程度。",
    "Max worktrees": "最大工作树数量",
    "Maximum number of Cursor-managed worktrees to retain across all workspaces. Older worktrees are removed first.": "在所有工作区中保留的 Cursor 托管工作树最大数量。较旧的工作树会优先移除。",
    "Max total size (GB)": "最大总大小（GB）",
    "Maximum total size in GB across all Cursor-managed worktrees. Set to 0 to disable the size limit.": "所有 Cursor 托管工作树的最大总大小（GB）。设置为 0 可禁用大小限制。",
    "Cursor-managed worktrees": "Cursor 托管的工作树",
    "No Cursor-managed worktrees on this machine.": "此设备上没有 Cursor 托管的工作树。",
    "Sync layouts across windows": "跨窗口同步布局",
    "When enabled, all windows share the same layout": "启用后，所有窗口共享相同的布局",
    "Choose between light, dark, or high contrast themes": "在浅色、深色或高对比度主题之间选择",
    "Choose a tint color": "选择一种强调色",
    "Control how strongly the tint is applied": "控制强调色应用的强度",
    "Reduce Transparency": "降低透明度",
    "Replace translucent surfaces with opaque backgrounds": "使用不透明背景替换半透明界面",
    "Compact Terminal Tool Calls": "紧凑显示终端工具调用",
    "Show terminal commands in compact view by default": "默认以紧凑视图显示终端命令",
    "UI Font Size": "界面字体大小",
    "Font size for the Cursor user interface": "Cursor 用户界面的字体大小",
    "Code Font Size": "代码字体大小",
    "Font size for code editors and diffs": "代码编辑器和差异视图的字体大小",
    "UI Font Family": "界面字体",
    "Override the Cursor user interface typeface": "覆盖 Cursor 用户界面的字体",
    "Code Font Family": "代码字体",
    "Override the font for code editors and diffs": "覆盖代码编辑器和差异视图的字体",
    "System font": "系统字体",
    "System monospace": "系统等宽字体",
    "Font Smoothing": "字体平滑",
    "Use native macOS font anti-aliasing": "使用 macOS 原生字体抗锯齿",
    "Hide Email Address": "隐藏邮箱地址",
    "Partially mask your email address in the Cursor user interface": "在 Cursor 用户界面中部分遮盖您的邮箱地址",
    "Editor Settings": "编辑器设置",
    "Configure font, formatting, minimap and more": "配置字体、格式化、缩略图等",
    "Keyboard Shortcuts": "键盘快捷键",
    "Configure keyboard shortcuts": "配置键盘快捷键",
    "Import Settings from VS Code": "从 VS Code 导入设置",
    "Import settings, extensions, and keybindings from VS Code": "导入 VS Code 的设置、扩展和快捷键绑定",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "Layout": "布局",
    "Status Bar": "状态栏",
    "Show status bar": "显示状态栏",
    "Auto-hide editor when empty": "空闲时自动隐藏编辑器",
    "When all editors are closed, hide the editor area and maximize chat": "关闭所有编辑器时，隐藏编辑器并最大化聊天窗口",
    "Notifications": "通知",
    "System Notifications": "系统通知",
    "Show system notifications when Agent completes or needs attention": "智能体完成任务或需要注意时显示系统通知",
    "System Tray Icon": "系统托盘图标",
    "Show Cursor in system tray": "在系统托盘显示 Cursor",
    "Completion Sound": "完成提示音",
    "Play a sound when Agent finishes responding": "智能体完成响应时播放提示音",
    "Privacy": "隐私",
    "Rules, Skills, Subagents": "规则、技能与子智能体",
    "Tools & MCP": "工具与 MCP",
    "Indexing & Docs": "索引与文档",
    "Cloud Agents": "云端智能体",
    "Team Plan": "团队版",
    "Plugins": "插件",
    "Search settings": "搜索设置",
    "VS Code Settings": "VS Code 设置",
    "Open VS Code Settings": "打开 VS Code 设置",
    "Plan & Usage": "套餐与用量",
    "Manage View": "管理视图",
    "Current Plan": "当前套餐",
    "Ultra Plan": "Ultra 套餐",
    "Pro+ Plan": "Pro+ 套餐",
    "Pro Plan": "Pro 套餐",
    "Free Plan": "免费套餐",
    "Pro+ Trial": "Pro+ 试用",
    "Pro Trial": "Pro 试用",

    // ── API Keys / Provider keys ──
    "API Keys": "API 密钥",
    "OpenAI API Key": "OpenAI API 密钥",
    "You can put in your OpenAI key to use OpenAI models at cost.": "你可以填写你的 OpenAI 密钥，以按成本使用 OpenAI 模型。",
    "You can put in": "你可以填写",
    "You can put in ": "你可以填写 ",
    "your OpenAI key": "你的 OpenAI 密钥",
    "to use OpenAI models at cost.": "以按成本使用 OpenAI 模型。",
    " to use OpenAI models at cost.": "，以按成本使用 OpenAI 模型。",
    "Enter your OpenAI API Key": "请输入 OpenAI API 密钥",
    "Override OpenAI Base URL": "覆盖 OpenAI 基础 URL",
    "Change the base URL for OpenAI API requests.": "修改 OpenAI API 请求的基础 URL。",
    "Anthropic API Key": "Anthropic API 密钥",
    "You can put in your Anthropic key to use Claude at cost. When enabled, this key will be used for all models beginning with \"claude-\".": "你可以填写你的 Anthropic 密钥，以按成本使用 Claude。启用后，此密钥将用于所有以 \"claude-\" 开头的模型。",
    "your Anthropic key": "你的 Anthropic 密钥",
    "to use Claude at cost. When enabled, this key will be used for all models beginning with \"claude-\".": "以按成本使用 Claude。启用后，此密钥将用于所有以 \"claude-\" 开头的模型。",
    " to use Claude at cost. When enabled, this key will be used for all models beginning with \"claude-\".": "，以按成本使用 Claude。启用后，此密钥将用于所有以 \"claude-\" 开头的模型。",
    "Enter your Anthropic API Key": "请输入 Anthropic API 密钥",
    "Google API Key": "Google API 密钥",
    "You can put in your Google AI Studio key to use Google models at-cost.": "你可以填写你的 Google AI Studio 密钥，以按成本使用 Google 模型。",
    "your Google AI Studio key": "你的 Google AI Studio 密钥",
    "to use Google models at-cost.": "以按成本使用 Google 模型。",
    " to use Google models at-cost.": "，以按成本使用 Google 模型。",
    "Enter your Google AI Studio API Key": "请输入 Google AI Studio API 密钥",
    "Enter your Azure OpenAI API Key": "请输入 Azure OpenAI API 密钥",
    "Azure OpenAI": "Azure OpenAI",
    "Configure Azure OpenAI to use OpenAI models through your Azure account.": "配置 Azure OpenAI，通过你的 Azure 账号使用 OpenAI 模型。",
    "Base URL": "基础 URL",

    "Approvals & Execution for commands, MCP and more": "命令、MCP 等审批与执行",
    "Run Mode": "运行模式",
    "Auto-Run Mode": "自动运行模式",
    "Choose how Agents run tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "Choose how Agent runs tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "Commands that are allowlisted will run automatically.": "列入白名单的命令将自动运行。",
    "Command Allowlist": "命令白名单",
    "Commands that can run automatically": "可自动运行的命令",
    "MCP Allowlist": "MCP 白名单",
    "MCP tools that can run automatically. Format: 'server:tool', 'server:*' for all tools from a server, '*:tool' for a tool from any server, or *:* for all tools from all servers": "可自动运行的 MCP 工具。格式：'server:tool'、'server:*' 表示某服务器的全部工具、'*:tool' 表示任意服务器的某工具、*:* 表示所有服务器的所有工具",
    "Fetch Domain Allowlist": "请求域名白名单",
    "Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.": "智能体可自动请求的域名。使用 '*' 匹配所有域名，'*.example.com' 匹配通配符子域名。",
    "Auto-Run Network Access": "自动运行网络访问",
    "Control which network requests are allowed when commands run in the sandbox. Edit allowed/denied domains in sandbox.json in your workspace.": "控制命令在沙盒中运行时允许哪些网络请求。可在工作区的 sandbox.json 中编辑允许或拒绝的域名。",
    "Auto-Approved Mode Transitions": "自动批准的模式切换",
    "Mode transitions that will be automatically approved without prompting.": "无需提示即自动批准的模式切换。",
    "Browser Protection": "浏览器保护",
    "Prevent Agent from automatically running Browser tools": "阻止智能体自动运行浏览器工具",
    "MCP Tools Protection": "MCP 工具保护",
    "Prevent Agent from automatically running MCP tools": "阻止智能体自动运行 MCP 工具",
    "File-Deletion Protection": "文件删除保护",
    "Prevent Agent from deleting files automatically": "阻止智能体自动删除文件",
    "External-File Protection": "外部文件保护",
    "Prevent Agent from creating or modifying files outside of the workspace automatically": "阻止智能体自动创建或修改工作区外的文件",
    "Default Location": "默认位置",
    "Where to open new agents": "新智能体的打开位置",
    "Text Size": "文字大小",
    "Adjust the conversation text size": "调整对话文字大小",
    "Ask Every Time": "每次询问",
    "Allowlist": "白名单",
    "Use Allowlist": "使用白名单",
    "Run Everything": "运行所有",
    "Auto-Run in Sandbox": "在沙盒中自动运行",
    "Run Everything (Unsandboxed)": "运行所有（非沙盒）",
    "Ask for permission before running each operation": "每次操作前请求许可",
    "Automatically run operations after you approve them once": "在您批准一次后自动运行操作",
    "Automatically run all operations without asking for permission": "无需请求许可，自动运行所有操作",
    "Tools will auto-run in a sandbox if possible, otherwise respect the allowlist or ask for approval": "工具会尽可能在沙盒中自动运行，否则遵循白名单或请求批准",
    "sandbox.json Only": "仅 sandbox.json",
    "sandbox.json + Defaults": "sandbox.json + 默认值",
    "Allow All": "全部允许",
    "Sandboxed network access is disabled by your admin.": "沙盒网络访问已被管理员禁用。",
    "Sandboxed network access is controlled by your admin. You can still edit allowed/denied domains in sandbox.json in your workspace, but admin policy takes precedence.": "沙盒网络访问由管理员控制。您仍可在工作区的 sandbox.json 中编辑允许或拒绝的域名，但管理员策略优先。",
    "Smart Allowlist": "智能白名单",
    "Use AI-powered command classification to intelligently match commands against allowlist patterns and suggest sandbox modes": "使用 AI 命令分类智能匹配白名单模式并建议沙盒模式",
    "Settings": "设置",
    "Extra Large": "超大",
    "Cursor Tab": "Cursor Tab 补全",
    "Window Layout": "窗口布局",
    "Switch between Agent and Editor default layouts": "在智能体和编辑器默认布局之间切换",
    "Title Bar": "标题栏",
    "Show title bar in agent layout": "在智能体布局中显示标题栏",
    "Show status bar at the bottom of the window": "在窗口底部显示状态栏",
    "Review Control Location": "审查控件位置",
    "Show inline diff review controls in top level breadcrumbs or floating island": "在顶部面包屑或浮动面板中显示内联差异审查控件",
    "Breadcrumb": "面包屑",
    "Island": "浮动面板",
    "Context-aware, multi-line suggestions around your cursor based on recent edits": "基于最近编辑，在光标周围提供上下文感知的多行建议",
    "Partial Accepts": "部分接受",
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+右箭头接受建议的下一个单词",
    "Suggestions While Commenting": "注释时建议",
    "Allow Tab to trigger while in a comment region": "允许在注释区域中触发 Tab 补全",
    "Whitespace-Only Suggestions": "仅空白建议",
    "Suggest edits like new lines and indentation that modify whitespace only": "仅建议修改空白的编辑，如换行和缩进",
    "Automatically import necessary modules for TypeScript": "自动导入 TypeScript 所需的模块",
    "Auto Import for Python": "Python 自动导入",
    "Enable auto import for Python. This is a beta feature.": "启用 Python 自动导入。这是一个测试功能。",
    "Provide domain-specific knowledge and workflows for the agent": "为智能体提供特定领域的知识和工作流",
    "Include third-party Plugins, Skills, and other configs": "包含第三方插件、技能和其他配置",
    "Automatically import agent configs from other tools": "自动从其他工具导入智能体配置",
    "Use Rules to guide agent behavior, like enforcing best practices or coding standards. Rules can be applied always, by file path, or manually.": "使用规则引导智能体行为，例如强制执行最佳实践或编码标准。规则可以始终应用、按文件路径应用或手动应用。",
    "No Rules Yet": "暂无规则",
    "Create rules to guide Agent behavior": "创建规则来引导智能体行为",
    "New User Rule": "新建用户规则",
    "New Project Rule": "新建项目规则",
    "Could Not Load Rules": "无法加载规则",
    "Failed to load workspace rules.": "加载工作区规则失败。",
    "Loading Rules...": "正在加载规则...",
    "Rule content...": "规则内容...",
    "Style request, response language, tone...": "风格要求、回复语言、语气...",
    "Applied intelligently": "智能应用",
    "Content is required.": "内容不能为空。",
    "File pattern is required when applying to specific files.": "应用到指定文件时必须填写文件模式。",
    "Failed to save changes. Please try again.": "保存失败，请重试。",
    "Incorrect format, fix with agent": "格式不正确，使用智能体修复",
    "Delete Rule": "删除规则",
    "Cannot delete team rules": "无法删除团队规则",
    "Show all": "显示全部",
    "Show less": "收起",
    "[Untitled]": "[未命名]",
    "Skills are specialized capabilities that help the agent accomplish specific tasks. Skills will be invoked by the agent when relevant or can be triggered manually with / in chat.": "技能是帮助智能体完成特定任务的专业能力。智能体会在相关时自动调用技能，也可在聊天中通过 / 手动触发。",
    "No Skills Yet": "暂无技能",
    "Skills help the agent accomplish specific tasks": "技能帮助智能体完成特定任务",
    "New Skill": "新建技能",
    "Could Not Load Skills": "无法加载技能",
    "Failed to load workspace skills.": "加载工作区技能失败。",
    "Loading Skills...": "正在加载技能...",
    "Create specialized agents for complex tasks. Subagents can be invoked by the agent to handle focused work in parallel.": "创建用于复杂任务的专业智能体。子智能体可被主智能体调用，以并行处理专项工作。",
    "No Subagents Yet": "暂无子智能体",
    "Create specialized agents to handle focused tasks": "创建专业智能体来处理专项任务",
    "New Subagent": "新建子智能体",
    "Could Not Load Subagents": "无法加载子智能体",
    "Failed to load workspace subagents.": "加载工作区子智能体失败。",
    "Loading Subagents...": "正在加载子智能体...",
    "Create reusable workflows triggered with / prefix in chat. Use commands to standardize processes and make common tasks more efficient.": "创建在聊天中通过 / 前缀触发的可复用工作流。使用命令标准化流程，提高常见任务的效率。",
    "No Commands Yet": "暂无命令",
    "Create commands to build reusable workflows": "创建命令以构建可复用工作流",
    "New Command": "新建命令",
    "Could Not Load Commands": "无法加载命令",
    "Failed to load workspace commands.": "加载工作区命令失败。",
    "Loading Commands...": "正在加载命令...",
    "+ New": "+ 新建",

    // ── 智能体设置 ──
    "Auto-Clear Chat": "自动清除聊天",
    "After periods of inactivity, open the Agent Pane to a new conversation": "一段时间不活动后，将智能体面板打开为新对话",
    "Submit with Ctrl + Enter": "使用 Ctrl + Enter 提交",
    "When enabled, Ctrl + Enter submits chat and Enter inserts a newline": "启用后，Ctrl + Enter 提交聊天，Enter 插入换行",
    "Max Tab Count": "最大标签页数",
    "Limit how many chat tabs can be open at once": "限制同时打开的聊天标签页数量",
    "Queue Messages": "消息队列",
    "Adjust the default behavior of sending a message while Agent is running": "调整智能体运行时发送消息的默认行为",
    "Send after current message": "当前消息后发送",
    "Stop & send right away": "立即停止并发送",
    "Usage Summary": "用量摘要",
    "When to show the usage summary at the bottom of the chat pane": "何时在聊天面板底部显示用量摘要",
    "Agent Autocomplete": "智能体自动补全",
    "Contextual suggestions while prompting Agent": "向智能体提问时提供上下文建议",
    "Authentication error": "身份验证错误",
    "If you are logged in, try logging out and back in.": "如果您已登录，请尝试退出后重新登录。",
    "Copy Request": "复制请求",

    // ── Agent Review ──
    "Start Agent Review on Commit": "代码提交时启动智能体审查",
    "Automatically review your changes for issues after each commit": "在每次提交后自动审查您的更改是否存在问题",
    "Include Submodules in Agent Review": "在智能体审查中包含子模块",
    "Include changes from Git submodules in the review": "在审查中包含 Git 子模块的更改",
    "Include Untracked Files in Agent Review": "在审查中包含未跟踪文件",
    "Include untracked files (new files not yet added to Git) in the review": "在审查中包含未跟踪文件（尚未添加到 Git 的新文件）",
    "Default Approach": "默认方式",
    "Choose between quick or more thorough, higher-cost analysis": "选择快速或更彻底、成本更高的分析",
    "Auto-Approve Mode Transitions": "自动批准模式切换",
    "Allow Agent to switch modes without asking first, such as Agent to Plan or Agent to Debug. When off, Cursor asks before switching.": "允许智能体在不先询问的情况下切换模式，例如从智能体切换到计划或调试。关闭时，Cursor 会在切换前询问。",
    "Subagents": "子智能体",
    "Explore subagent model": "探索子智能体模型",
    "Choose Explore subagent model": "选择探索子智能体模型",
    "The Explore subagent is used to do initial research for the main agent": "探索子智能体用于为主智能体进行初始研究",
    "Select model": "选择模型",
    "Select model count": "选择模型数量",
    "Inherit from parent": "继承父级设置",
    "Reset to default": "重置为默认值",
    "Max Mode required": "需要 Max 模式",
    "Subagent model overrides will only be used in Max Mode": "子智能体模型覆盖仅会在 Max 模式中使用",
    "Follow-Up Prompt Suggestions": "后续提示建议",
    "Suggest a follow-up for the Agent": "为智能体建议后续提示",

    // ── Context & Applied Changes ──
    "Web Search Tool": "网络搜索工具",
    "Allow Agent to search the web for relevant information": "允许智能体在网络上搜索相关信息",
    "Auto-Accept Web Search": "自动接受网络搜索",
    "Skip approval dialog; Agent may run web searches automatically": "跳过批准对话；智能体可自动运行网络搜索",
    "Web Fetch Tool": "网页获取工具",
    "Allow Agent to fetch content from URLs": "允许智能体从 URL 获取内容",
    "Hierarchical Cursor Ignore": "分层 Cursor 忽略",
    "Apply .cursorignore files to all subdirectories. Changing this setting will require a restart of Cursor.": "将 .cursorignore 文件应用到所有子目录。更改此设置需要重启 Cursor。",
    "Ignore Symlinks in Cursor Ignore Search": "在 Cursor 忽略搜索中忽略符号链接",
    "Use with caution. Skip symlinks during .cursorignore file discovery. Only enable if your repository has many symlinks and all .cursorignore files are reachable without them. Changing this setting will require a restart of Cursor.": "谨慎使用。在发现 .cursorignore 文件时跳过符号链接。仅当您的仓库存有许多符号链接，且没有符号链接也能访问所有 .cursorignore 文件时才启用。更改此设置需要重启 Cursor。",
    "Applying Changes": "应用更改",
    "Inline Diffs": "内联差异",
    "Show inline diff decorations in the editor instead of only showing changes in the review panel": "在编辑器中显示内联差异装饰，而不是仅在审查面板中显示更改",
    "Jump to Next Diff on Accept": "接受时跳转到下一个差异",
    "Automatically jump to the next diff when accepting changes with Ctrl+Y": "使用 Ctrl+Y 接受更改时自动跳转到下一个差异",
    "Auto Format on Agent Finish": "智能体完成时自动格式化",
    "Automatically format files when the agent finishes": "智能体完成任务时自动格式化文件",

    // ── Inline Editing & Terminal ──
    "Inline Editing & Terminal": "内联编辑与终端",
    "Legacy Terminal Tool": "旧版终端工具",
    "Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations": "在智能体模式下使用旧版终端工具，适用于 shell 配置不受支持的系统",
    "Toolbar on Selection": "选中时显示工具栏",
    "Show Add to Chat & Quick Edit buttons when selecting code": "选择代码时显示“添加到聊天”和“快速编辑”按钮",
    "Auto-Parse Links": "自动解析链接",
    "Automatically parse links when pasted into Quick Edit (Ctrl+K) input": "粘贴到快速编辑 (Ctrl+K) 输入框时自动解析链接",
    "Themed Diff Backgrounds": "主题差异背景",
    "Use themed background colors for inline code diffs": "为内联代码差异使用主题背景色",
    "Terminal Hint": "终端提示",
    "Show a hint for Ctrl+K in the Terminal": "在终端中显示 Ctrl+K 提示",
    "Preview Box for Terminal Ctrl+K": "终端 Ctrl+K 的预览框",
    "Use a preview box instead of streaming responses directly into the shell": "使用预览框而不是将响应直接流式传输到 shell 中",
    "Collapse Auto-Run Commands": "折叠自动运行命令",
    "Collapse auto-run command output by default in Terminal command previews": "在终端命令预览中默认折叠自动运行的命令输出",

    // ── Voice Mode & Attribution ──
    "Voice Mode": "语音模式",
    "Submit Keywords": "提交关键字",
    "Custom keywords that trigger auto-submit in voice mode. Only single words (no spaces) are allowed. Punctuation and capitalization are ignored.": "在语音模式下触发自动提交的自定义关键字。仅允许单个单词（无空格）。忽略标点符号和大小写。",
    "Attribution": "代码署名",
    "Commit Attribution": "提交署名",
    "Mark Agent commits as 'Made with Cursor'": "将智能体提交标记为 'Made with Cursor'",
    "PR Attribution": "PR 署名",
    "Mark pull requests as made with Cursor": "将拉取请求标记为使用 Cursor 制作",

    // ── Git ──
    "Branch Prefix": "分支前缀",
    "Prefix for new branches created by Agent (e.g., cursor/, username/)": "智能体创建新分支时使用的前缀（例如 cursor/、username/）",

    // ── Privacy ──
    "Privacy Mode": "隐私模式",
    "Privacy Mode (Legacy)": "隐私模式（旧版）",
    "Your code data will not be trained on or used to improve the product. Code may be stored to provide features such as Background Agent.": "您的代码数据不会被用于训练或改进产品。代码可能会被存储以提供后台智能体等功能。",
    "Your code data will not be trained on or used to improve the product. We will not store your code.": "您的代码数据不会被用于训练或改进产品。我们不会存储您的代码。",
    "Privacy Mode (Legacy) is enabled. Background Agent and some features not available.": "隐私模式（旧版）已启用。后台智能体和部分功能不可用。",
    "Switch to Privacy Mode": "切换到隐私模式",
    "Data Sharing is controlled by the team admin. Configure here.": "数据共享由团队管理员控制。在此配置。",
    "Share Data": "共享数据",
    "Improve Cursor for everyone": "帮助所有人改进 Cursor",
    "No training. Code may be stored for Background Agent and other features.": "不用于训练。代码可能会被存储，以支持后台智能体和其他功能。",
    "No training and no storage. Background Agent and other features that require code storage will be disabled.": "不用于训练，也不存储。后台智能体和其他需要代码存储的功能将被禁用。",
    "More Options": "更多选项",

    // ── Miscellaneous ──
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+RightArrow 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // ── Usage Limits ──
    "Increase limits for faster responses": "提高限制以获得更快的响应",
    "You're over your current usage limit and your requests are being processed with Auto in the slow queue.": "您已超出当前配置的使用量限制，您的请求正以临时排队方式在慢速队列中处理。",
    "Set new limit": "设置新限制",
    "On-Demand Usage": "按需用量",
    "On-Demand Spending": "按需消费",
    "On-Demand usage is consumed after a usage limit is reached, and is billed in arrears.": "达到用量限制后会消耗按需用量，并在之后计费。",
    "On-demand spending is currently disabled": "按需消费当前已禁用",
    "Monthly Limit": "月度限额",
    "Set a fixed amount or make it unlimited.": "设置固定额度，或设为无限制。",
    "Your plan includes at least $": "您的套餐至少包含 $",
    " of API usage.": " 的 API 用量。",

    // ── Cloud / Background Agents ──
    "Get Started": "开始使用",
    "Cloud Agents Unavailable": "云端智能体不可用",
    "Cloud Agents require data storage to function.": "云端智能体需要数据存储才能运行。",
    "Privacy Mode Enabled": "隐私模式已启用",
    "Cloud Agents are not available when your privacy mode is set to disable data storage. To use Cloud Agents, please update your privacy settings to allow data storage.": "当隐私模式设置为禁用数据存储时，云端智能体不可用。要使用云端智能体，请更新隐私设置以允许数据存储。",
    "Open Privacy Settings": "打开隐私设置",
    "Cloud Agents require a Git repository in an open folder.": "云智能体需要打开的文件夹中包含 Git 仓库。",
    "Loading Cloud Agents settings...": "正在加载云端智能体设置...",
    "Open a folder that contains a Git repository to configure Cloud Agents.": "打开包含 Git 仓库的文件夹以配置云端智能体。",
    "Manage Settings": "管理设置",
    "Open a Git repository": "打开 Git 仓库",
    "Background agents only work in folders with a git repository.": "后台智能体仅在包含 git 仓库的文件夹中工作。",
    "Please open a folder that contains a git repository to use this feature.": "请打开包含 git 仓库的文件夹以使用此功能。",

    // ── Extensions / Marketplace ──
    "No Plugins": "暂无插件",
    "Browse the marketplace or import custom plugins to extend Cursor with Skills, Rules, Agents, Hooks, and MCPs.": "浏览插件市场或导入自定义插件，用技能、规则、智能体、钩子和 MCP 扩展 Cursor。",
    "Browse the marketplace or import custom plugins to extend": "浏览插件市场或导入自定义插件来扩展",
    "Cursor with Skills, Rules, Agents, Hooks, and MCPs.": "Cursor 的技能、规则、智能体、钩子和 MCP。",
    "Add Plugin": "添加插件",
    "Add Plugins": "添加插件",
    "Search the marketplace": "搜索插件市场",
    "Loading plugins...": "正在加载插件...",
    "No result": "无结果",
    "No Result": "无结果",
    "No results": "无结果",
    "No results found": "未找到结果",
    "No Results": "无结果",
    "No Results Found": "未找到结果",
    "No files found": "未找到文件",
    "No matches found": "未找到匹配项",
    "No plugins found": "未找到插件",
    "No plugins found in this repository.": "此仓库中未找到插件。",
    "No plugins match your search.": "没有插件匹配你的搜索。",
    "Try changing your search query": "请尝试修改搜索条件",
    "Try a different search term or browse by category": "请尝试其他搜索词或按分类浏览",
    "Try different filters": "请尝试不同筛选条件",
    "All plugins have been added.": "所有插件均已添加。",
    "All plugins from this repository have already been added.": "此仓库中的所有插件均已添加。",
    "Add plugins or import from GitHub to make them available for your team.": "添加插件或从 GitHub 导入，使团队可以使用它们。",
    "Import Marketplace...": "导入插件市场...",
    "Manage plugins": "管理插件",
    "Extend Cursor with Skills, Rules, Agents, Hooks, and MCPs": "使用技能、规则、智能体、钩子和 MCP 扩展 Cursor",
    "Browse MCPs": "浏览 MCP",
    "Search anything": "搜索任何内容",
    "Browse Marketplace": "浏览插件市场",

    // ── Common visible UI states ──
    "Rendering diagram...": "正在渲染图表...",
    "Mermaid Syntax Error": "Mermaid 语法错误",
    "View diagram source": "查看图表源码",
    "Open in Terminal Pane": "在终端面板中打开",
    "Add to Allowlist and Run": "添加到白名单并运行",
    "Empty directory": "空目录",
    "No diagnostics found": "未发现诊断信息",
    "No MCP resources available": "暂无可用 MCP 资源",
    "Waiting for upload...": "正在等待上传...",
    "This agent was working on ": "此智能体正在处理 ",
    "Don't ask again": "不再询问",
    "Stay on Current Branch": "留在当前分支",
    "Agent disconnected": "智能体已断开连接",
    "Context Usage": "上下文用量",
    "Search or Paste Link": "搜索或粘贴链接",
    "OAuth Client ID (optional)": "OAuth 客户端 ID（可选）",
    "OAuth Client Secret (optional)": "OAuth 客户端密钥（可选）",
    "Add MCP Server": "添加 MCP 服务器",
    "Clear variables": "清除变量",
    "Plugin Settings": "插件设置",
    "Marketplace Settings": "插件市场设置",
    "Marketplace Access": "插件市场访问权限",
    "Select who can see and use plugins from this team marketplace": "选择谁可以查看和使用此团队插件市场中的插件",
    "Enable Auto Refresh": "启用自动刷新",
    "Automatically update plugins when changes are pushed to the repository": "当变更推送到仓库时自动更新插件",
    "Plugin Repository": "插件仓库",
    "Fetch marketplace plugins from the GitHub repository": "从 GitHub 仓库获取插件市场插件",
    "Remove Marketplace": "移除插件市场",
    "Remove marketplace?": "移除插件市场？",
    "Delete Marketplace": "删除插件市场",
    "Delete marketplace?": "删除插件市场？",
    "This marketplace and its access settings will be removed. The source repository won't be affected.": "将移除此插件市场及其访问设置。源仓库不会受到影响。",
    "This marketplace and its access settings will be removed. The repository won't be affected.": "将移除此插件市场及其访问设置。仓库不会受到影响。",
    "This marketplace will be removed from your account. The source repository won't be affected.": "将从你的账号中移除此插件市场。源仓库不会受到影响。",
    "Available Marketplaces": "可用插件市场",
    "Access Settings": "访问设置",
    "Plugin Installation": "插件安装",
    "Add for Myself": "为自己添加",
    "Add to Project": "添加到项目",
    "Finishing setup...": "正在完成设置...",
    "Open in Editor": "在编辑器中打开",
    "Open debug logs": "打开调试日志",
    "Restore default parameters": "恢复默认参数",
    "Uncommitted Changes": "未提交变更",
    "Modes, skills, MCPs and more": "模式、技能、MCP 等",
    "Download file": "下载文件",
    "Download image": "下载图片",
    "Open external link?": "打开外部链接？",
    "You're about to visit an external website.": "你即将访问外部网站。",
    "Download diagram": "下载图表",
    "Download diagram as SVG": "下载 SVG 图表",
    "Download diagram as PNG": "下载 PNG 图表",
    "Download diagram as MMD": "下载 MMD 图表",
    "View fullscreen": "全屏查看",
    "Exit fullscreen": "退出全屏",
    "Copy table as CSV": "复制为 CSV 表格",
    "Copy table as TSV": "复制为 TSV 表格",
    "Download table": "下载表格",
    "Download table as CSV": "下载 CSV 表格",
    "Download table as Markdown": "下载 Markdown 表格",
    "Reset zoom and pan": "重置缩放和平移",
    "Loading diagram...": "正在加载图表...",
    "No Automations Yet": "暂无自动化",
    "New Automation": "新建自动化",
    "Run agents on a schedule or automatically in response to events. Billed at plan rates.": "按计划运行智能体，或响应事件自动运行。按套餐费率计费。",
    "No results found.": "未找到结果。",
    "No results for": "没有结果匹配",
    "Search channels or paste channel ID...": "搜索频道或粘贴频道 ID...",
    "Loading channels...": "正在加载频道...",
    "No channels available": "暂无可用频道",
    "Add channel ID ": "添加频道 ID ",
    "Any channel": "任意频道",
    "Selected": "已选择",
    "Manage Marketplace": "管理插件市场",
    "Date range": "日期范围",
    "Rows per page": "每页行数",
    "Search Plugins, Skills, Tools, Subagents, Commands...": "搜索插件、技能、工具、子智能体、命令...",
    "All Marketplaces": "所有插件市场",
    "Debug Logs": "调试日志",
    "Waiting for log entries...": "正在等待日志条目...",
    "Clear Logs": "清空日志",
    "Reproduction Steps": "复现步骤",
    "Mark Fixed": "标记为已修复",
    "Load Diff": "加载差异",
    "Generated files are not rendered by default.": "默认不渲染生成文件。",
    "Large diffs are hidden by default.": "默认隐藏大型差异。",
    "Diff content not available": "差异内容不可用",
    "This file changed, but a text diff could not be rendered.": "此文件已更改，但无法渲染文本差异。",
    "Agent blocked": "智能体已被阻止",
    "Up to date": "已是最新",
    "Ready to save": "准备保存",
    "Setting up": "正在设置",
    "Anything else?": "还有其他问题吗？",
    "Add Models": "添加模型",
    "Your admin has disabled this option.": "你的管理员已禁用此选项。",
    "Show all models...": "显示所有模型...",
    "MAX Mode": "MAX 模式",
    "Use Multiple Models": "使用多个模型",
    "Enable MAX Mode": "启用 MAX 模式",
    "Search models": "搜索模型",
    "No models found": "未找到模型",
    "Move to Local": "移动到本地",
    "Checkout branch locally": "在本地检出分支",
    "Checkout & Move to Local": "检出并移动到本地",
    "Checkout branch and convert agent to local mode": "检出分支并将智能体转换为本地模式",
    "You have uncommitted changes in your working tree. Choose an option, then continue.": "你的工作树中有未提交的更改。请选择一个选项，然后继续。",
    "Do not ask me again": "不再询问我",
    "Paste as one line": "粘贴为一行",
    "Add an agent to get started": "添加一个智能体以开始使用",
    "Todo description...": "待办描述...",
    "Build in New Agent": "在新智能体中构建",
    "Add a to-do to get started": "添加一个待办以开始使用",
    "Add to Chat": "添加到聊天",
    "Plan body...": "计划正文...",
    "Save to workspace": "保存到工作区",
    "Build in Parallel": "并行构建",
    "Copy as Markdown": "复制为 Markdown",
    "Find in Plan": "在计划中查找",
    "Save to Workspace": "保存到工作区",
    "View Plan": "查看计划",
    "Error loading plugin": "加载插件出错",
    "Try in Chat": "在聊天中试用",
    "Import from GitHub": "从 GitHub 导入",
    "Enter a GitHub repository URL containing a plugin marketplace": "输入包含插件市场的 GitHub 仓库 URL",
    "GitHub Repository URL": "GitHub 仓库 URL",
    "Open in Chat": "在聊天中打开",
    "View Details": "查看详情",
    "Remove from Cursor": "从 Cursor 中移除",
    "All files and folders": "所有文件和文件夹",
    "Add Skills": "添加技能",
    "Search MCP servers...": "搜索 MCP 服务器...",
    "Loading MCP servers...": "正在加载 MCP 服务器...",
    "No MCP servers": "暂无 MCP 服务器",
    "No MCP servers available": "暂无可用 MCP 服务器",
    "No MCP servers configured": "未配置 MCP 服务器",
    "No servers match your search": "没有服务器匹配你的搜索",
    "Open MCP Settings": "打开 MCP 设置",
    "Add agents, context, tools...": "添加智能体、上下文、工具...",
    "Loading skills...": "正在加载技能...",
    "No skills available": "暂无可用技能",
    "Waiting for logs": "正在等待日志",
    "SSH Hostname": "SSH 主机名",
    "Type in a host like user@host or select from SSH config": "输入 user@host 形式的主机，或从 SSH 配置中选择",
    "Rename tab": "重命名标签页",
    "Close Others": "关闭其他标签页",
    "Close to the Right": "关闭右侧标签页",
    "Close All": "全部关闭",
    "Commit changes": "提交更改",
    "Create a checkpoint commit with your current changes": "使用当前更改创建检查点提交",
    "Stash changes": "暂存更改",
    "Save your changes to a stash and restore them later": "将更改保存到 stash，稍后可恢复",
    "Discard changes": "放弃更改",
    "Delete your current uncommitted changes before switching": "切换前删除当前未提交的更改",
    "Temporarily save uncommitted work, then check out the cloud agent branch.": "临时保存未提交的工作，然后检出云端智能体分支。",
    "Create a checkpoint commit of your changes, then check out the branch.": "为你的更改创建检查点提交，然后检出该分支。",
    "Hidden from agent": "对智能体隐藏",
    "Leak scanned before commit": "提交前已扫描泄漏",
    "Available at runtime": "运行时可用",
    "Available at build": "构建时可用",
    "No files": "无文件",
    "Most Used": "最常用",
    "Failed to migrate agent": "迁移智能体失败",
    "Change run mode": "更改运行模式",
    "Add to allowlist": "添加到白名单",
    "MCP Servers": "MCP 服务器",
    "Cloud MCP Servers": "云端 MCP 服务器",
    "User MCP Servers": "用户 MCP 服务器",
    "Team MCP Servers": "团队 MCP 服务器",
    "Workspace MCP Servers": "工作区 MCP 服务器",
    "Home MCP Servers": "Home MCP 服务器",
    "Workspace MCP Tools": "工作区 MCP 工具",
    "Servers available to cloud agents.": "可供云端智能体使用的服务器。",
    "Servers available in this workspace.": "此工作区可用的服务器。",
    "Servers available from Home.": "Home 中可用的服务器。",
    "Sign In to View Cloud MCP Servers": "登录以查看云端 MCP 服务器",
    "Could Not Load Cloud MCP Servers": "无法加载云端 MCP 服务器",
    "Could Not Load Workspace MCP Servers": "无法加载工作区 MCP 服务器",
    "No User MCP Servers": "暂无用户 MCP 服务器",
    "No Team MCP Servers": "暂无团队 MCP 服务器",
    "Loading cloud MCP servers...": "正在加载云端 MCP 服务器...",
    "Loading user MCP servers...": "正在加载用户 MCP 服务器...",
    "Loading team MCP servers...": "正在加载团队 MCP 服务器...",
    "Loading workspace MCP servers...": "正在加载工作区 MCP 服务器...",
    "Failed to load cloud MCP servers.": "加载云端 MCP 服务器失败。",
    "Failed to load workspace MCP servers.": "加载工作区 MCP 服务器失败。",
    "Your personal cloud MCP servers.": "你的个人云端 MCP 服务器。",
    "Cloud MCP servers shared by your team.": "团队共享的云端 MCP 服务器。",
    "Add a personal cloud MCP server to make it available to your cloud agents.": "添加个人云端 MCP 服务器，使云端智能体可以使用它。",
    "Team admins can configure shared MCP servers in the dashboard.": "团队管理员可在控制台配置共享 MCP 服务器。",
    "Open Dashboard": "打开控制台",
    "Add MCP": "添加 MCP",
    "Mermaid Diagram": "Mermaid 图表",
    "Tree outline": "树形大纲",
    "Apply to Specific Files & Folders": "应用到指定文件和文件夹",
    "Always applied": "始终应用",
    "Agent decides when to apply": "由智能体决定何时应用",
    "Create with Agent": "使用智能体创建",
    "Saving...": "正在保存...",
    "Plan and design before coding...": "编码前先规划和设计...",
    "Plan and design before coding": "编码前先规划和设计",
    "Debug and troubleshoot issues...": "调试并排查问题...",
    "Debug and troubleshoot issues": "调试并排查问题",
    "Ask questions without making changes...": "提问但不修改...",
    "Ask questions without making changes": "提问但不修改",
    "Files & Folders": "文件和文件夹",
    "Agent Stores": "智能体存储",
    "Past Chats": "历史聊天",
    "Branch (Diff with Main)": "分支（与 Main 对比）",
    "Mentions": "提及项",
    "Terminals": "终端",
    "Grep Search": "Grep 搜索",
    "Search files": "搜索文件",
    "Searching files": "正在搜索文件",
    "Searched files": "已搜索文件",
    "Search files attempted": "已尝试搜索文件",
    "Search files...": "搜索文件...",
    "Search actions...": "搜索操作...",
    "Search agents...": "搜索智能体...",
    "Search files, actions, agents...": "搜索文件、操作、智能体...",
    "Files": "文件",
    "Actions": "操作",
    "Files in workspace": "工作区文件",
    "Edit & Reapply": "编辑并重新应用",
    "Delete file": "删除文件",
    "Enable Run Everything?": "启用“运行所有”？",
    "Enable Run Everything": "启用运行所有",
    "Leave Ask Every Time?": "离开“每次询问”？",
    "Use Sandbox instead": "改用沙盒",
    "Use Allowlist instead": "改用白名单",
    "Continue": "继续",
    "Unsupported Model": "不支持的模型",
    "The model \"": "模型 \"",
    "\" is not supported. Please choose a different model.": "\" 不受支持。请选择其他模型。",
    "Connection stalled": "连接停滞",
    "Connection stalled repeatedly": "连接反复停滞",
    "The connection stalled. Please try again.": "连接停滞。请重试。",
    "Connection failed": "连接失败",
    "Connection failed repeatedly": "连接反复失败",
    "Connection failed. Please try again, or contact support if the issue persists.": "连接失败。请重试；如果问题持续存在，请联系支持。",
    "Connection failed. If the problem persists, please check your internet connection or VPN": "连接失败。如果问题持续存在，请检查你的网络连接或 VPN",
    "Clear the conversation and start fresh": "清空对话并重新开始",
    "Summarize the conversation": "总结对话",
    "Request an agent to review your code": "请求智能体审查你的代码",
    "Open Browser": "打开浏览器",
    "Open a browser for web interactions": "打开浏览器进行网页交互",
    "Install a plugin from the marketplace": "从插件市场安装插件",
    "Browse and install plugins from the Cursor marketplace. Type a search query after the command to find plugins.": "从 Cursor 插件市场浏览并安装插件。在命令后输入搜索词以查找插件。",
    "Uninstall an installed plugin": "卸载已安装插件",
    "Remove an installed plugin. Type a search query after the command to find plugins to uninstall.": "移除已安装插件。在命令后输入搜索词以查找要卸载的插件。",
    "Reset": "重置",
    "Summarize": "总结",

    // ── Agent errors ──
    "Agent Execution Timed Out": "智能体执行超时",
    "The agent execution provider did not respond in time. This may indicate the extension host is not running or is unresponsive.": "智能体执行提供程序未及时响应。这可能表示扩展主机未运行或无响应。",
    "Reload Window": "重新加载窗口",

    // ── Network ──
    "HTTP Compatibility Mode": "HTTP 兼容模式",
    "HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.": "推荐使用 HTTP/2 以实现低延迟流式传输。在某些企业代理和 VPN 环境中，可能需要降低兼容模式。",
    "Required Domains": "必需的域名",
    "These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.": "必须可访问这些域名，Cursor 才能正常工作。请将它们添加到您的防火墙或代理白名单中。",
    "Network Diagnostics": "网络诊断",
    "Check network connectivity to all Cursor services": "检查与所有 Cursor 服务的网络连接",

    // ── Update ──
    "Update Access": "更新通道",
    "By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.": "默认情况下，接收稳定版更新的通知。在抢先体验通道中，预发布版本可能不稳定，不建议用于生产环境。",
    "Extension RPC Tracer": "扩展 RPC 追踪器",
    "Log extension host RPC messages to JSON files viewable in Perfetto for performance analysis. Requires a restart to take effect.": "将扩展主机的 RPC 消息记录到 JSON 文件中，可在 Perfetto 中查看以进行性能分析。需要重启才能生效。",

    // ── Hooks ──
    "Hooks let you run custom scripts at specific points during the agent's execution to modify behavior, enforce policies, or add custom logging.": "钩子允许您在智能体执行的特定点运行自定义脚本，以修改行为、强制执行策略或添加自定义日志。",
    "Configured Hooks": "已配置的钩子",
    "Configuration Errors": "配置错误",
    "Add a hooks.json file to your user, project, or enterprise config to start running custom scripts.": "在用户、项目或企业配置中添加 hooks.json 文件，即可开始运行自定义脚本。",
    "No hooks configured": "未配置钩子",
    "No hook executions yet": "暂无钩子执行记录",

    // ── Tools / Browser ──
    "Authentication": "身份验证",
    "Wait for MCP Authentication": "等待 MCP 身份验证",
    "Wait indefinitely to authenticate when prompted. When off, skip authentication prompts after 30 seconds.": "出现身份验证提示时会一直等待。关闭后，30 秒后跳过身份验证提示。",
    "Browser Automation": "浏览器自动化",
    "Connected to Browser Tab": "已连接到浏览器标签页",
    "Browser automation disabled": "浏览器自动化已禁用",
    "Checking status...": "正在检查状态...",
    "Show Localhost Links in Browser": "在浏览器中显示 Localhost 链接",
    "Automatically open localhost links in the Browser Tab": "自动在浏览器标签页中打开 localhost 链接",

    // ── Features / Documentation Links ──
    "Learn about Rules": "了解规则",
    "Learn about Skills": "了解技能",
    "Learn about Subagents": "了解子智能体",
    "Learn about Commands": "了解命令",
    "Learn more": "了解更多",
    "User Rule": "用户规则",
    "Project Rule": "项目规则",
    "Add from GitHub/GitLab": "从 GitHub/GitLab 添加",

    // ── Commands & MCP ──
    "Project Command": "项目命令",
    "User Command": "用户命令",
    "New MCP Server": "新建 MCP 服务器",
    "Add a Custom MCP Server": "添加自定义 MCP 服务器",
    "Open JSON": "打开 JSON",
    "Open user config": "打开用户配置",
    "Open project config": "打开项目配置",
    "Open enterprise config": "打开企业配置",

    // ── PR / Layout ──
    "PR Preferences": "PR 偏好设置",
    "Preferred PR destination": "首选 PR 打开位置",
    "Choose where PR links open across web, the desktop app and IDE.": "选择 PR 链接在网页、桌面应用和 IDE 中的打开位置。",

    // ── Composer modes ──
    "Plan, search, make edits, run commands": "规划、搜索、编辑并运行命令",
    "Plan, search, build anything": "规划、搜索、构建任何内容",
    "Coordinate long-horizon tasks with delegated subagents": "通过委派子智能体协调长期任务",
    "Create detailed plans for accomplishing tasks": "为完成任务创建详细计划",
    "Create structured plans with implementation steps": "创建包含实现步骤的结构化计划",
    "Systematically diagnose and fix bugs using runtime traces": "使用运行时追踪系统地诊断并修复问题",
    "Run and coordinate multiple tasks in parallel": "并行运行并协调多个任务",
    "Ask Cursor questions about your codebase": "向 Cursor 询问有关代码库的问题",
    "Special conversation mode for project-level discussions": "用于项目级讨论的特殊对话模式",

    // ── Models ──
    "Balanced quality and speed, recommended for most tasks": "平衡质量和速度，推荐用于大多数任务",
    "Multiple models require a Git repository.": "使用多模型功能需要 Git 仓库。",

    // ── Dialogs ──
    "Are you sure? This replaces your settings and extensions with your vscode ones. This cannot be undone.": "确定要继续吗？这将用您的 VS Code 设置和扩展替换当前的设置和扩展。此操作无法撤销。",
    "Reset \"Don't Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "Reset \"Don’t Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "See warnings and tips that you’ve hidden": "查看您已隐藏的警告和提示",
    "No Hidden Dialogs Yet": "暂无隐藏的弹窗",
    "You haven't marked any dialogs as \"Don't ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",
    "You haven’t marked any dialogs as \"Don’t ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",

    // ── 下面原本误放入了短词字典 ──
    "Submit with ": "使用 ",
    "When enabled, ": "启用后，",
    " submits chat and ": " 提交聊天，",
    " inserts a newline": " 插入换行",
    "Accept the next word of a suggestion via ": "使用 ",
    " accept the next word of a suggestion": " 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // Codebase 相关设置
    "Codebase": "代码库",
    "Codebase Indexing": "代码库索引",
    "Delete Index": "删除索引",
    "Index New Folders": "索引新文件夹",
    "Automatically index any new folders with fewer than 250,000 files": "自动索引少于 250,000 个文件的新文件夹",
    "View included files.": "查看已包含的文件。",
    "Team-Level Repository Control": "团队级代码库控制",
    "Disable AI features in specific repositories based on file pattern": "基于文件匹配模式在特定代码库中禁用 AI 功能",
    "Index Repositories for Instant Grep": "为 Instant Grep 索引代码库",
    "Automatically index repositories to speed up Grep searches. All data is stored locally.": "自动索引代码库以加速 Grep 搜索。所有数据均存储在本地。",
    "Crawl and index custom resources and developer docs": "爬取并索引自定义资源和开发者文档",
    "No Docs Added": "未添加文档",
    "Add Doc": "添加文档",
    "Increase limits for faster responses": "提升额度以获取更快响应",
    "Automatically jump to the next diff when accepting changes with ": "当接受更改时，自动跳转到下一个差异，借助 ",
    "Ignore Files in ": "忽略包含在 ",
    "Ignore Files in .cursorignore": "忽略 .cursorignore 中的文件",
    "Nightly Updates Apply Automatically": "每夜更新自动应用",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Learn about codebase indexing": "了解代码库索引",
    "Embed codebase for improved contextual understanding and knowledge. Embeddings and metadata are stored in the": "嵌入代码库以增强上下文理解和知识。嵌入向量和元数据存储在",
    ", but all code is stored locally.": "，但所有代码都存储在本地。",
    "Agent Review": "智能体审查",
    "Data Sharing is controlled by ": "数据共享由",
    "team admin.": "团队管理员控制。",
    "Nightly builds will silently download and install updates without prompting you.": "每夜版本将静默下载并安装更新，不会提示您。",
    "Keybinding: editor.action.inlineSuggest.acceptNextWord": "快捷键: editor.action.inlineSuggest.acceptNextWord",
    "Keybinding: ": "快捷键: ",
    "Keybinding:": "快捷键:",
    "Check recent git history": "检查最近 Git 历史",
    "Check current git status": "检查当前 Git 状态",
    "recent git history": "最近 Git 历史",
    "current git status": "当前 Git 状态",

    // ── Agent 面板、标签页菜单与搜索弹窗 ──
    "New Agent": "新建智能体",
    "Toggle Chat Pane": "切换聊天面板",
    "Maximize Chat": "最大化聊天",
    "Close Tab": "关闭标签页",
    "Close Other Tabs": "关闭其他标签页",
    "Close All Tabs": "关闭所有标签页",
    "Open Tab as Editor": "在编辑器中打开标签页",
    "Export Transcript": "导出对话记录",
    "Copy Request ID": "复制请求 ID",
    "Agent Settings": "智能体设置",
    "Search Agents...": "搜索智能体...",
    "Search Agents…": "搜索智能体…",
    "No matching agents": "未找到匹配的智能体",
    "Archived": "已归档"
};

const riskyShortWords = {
    "General": "通用",
    "Appearance": "外观",
    "VS Code Settings": "VS Code 设置",
    "Plan & Usage": "套餐与用量",
    "Current Plan": "当前套餐",
    "Agents": "智能体",
    // "Tab" 不可放入危险短词：workbench 键盘扫描表为 [n,n,"Tab",n,"Tab",n,"VK_TAB"]，
    // jsxRegex 会误匹配 49,"Tab" 导致 KeybindingService cannot be dispatched。
    // 设置页侧栏 Tab 项由 i18n-core.js scopedReplacements 的 tab:"Tab" 单独处理。
    "Models": "模型",
    "Plugins": "插件",
    "Hooks": "钩子",
    "Network": "网络",
    "Beta": "测试功能",
    "Marketplace": "插件市场",
    "Manage View": "管理视图",
    "Group By": "分组方式",
    "Sort By": "排序方式",
    "All": "全部",
    "User": "用户",
    "Search": "搜索",
    "Theme": "主题",
    "System": "系统",
    "Colors": "颜色",
    "Hue": "色相",
    "Intensity": "强度",
    "Chat": "聊天",
    "Agent": "智能体",
    "Editor": "编辑器",
    "Plan": "计划",
    "Triage": "分诊",
    "Spec": "规格",
    "Debug": "调试",
    "Multitask": "多任务",
    "Ask": "对话",
    "Project": "项目",
    "Typography": "字体排版",
    "Worktrees": "工作树",
    "Cleanup": "清理",
    "Subagents": "子智能体",
    "Git": "Git",
    "Docs": "官方文档",
    "Open": "打开",
    "Invite": "邀请",
    "Import": "导入",
    "Show": "显示",
    "Auto-Run": "自动运行",
    "Pane": "面板",
    "Small": "小",
    "Default": "默认",
    "Large": "大",
    "Imports": "导入",
    "Rules": "规则",
    "Skills": "技能",
    "Subagents": "子智能体",
    "Commands": "命令",
    "Unlimited": "无限制",
    "Disabled": "已禁用",
    "Fixed": "固定",
    "Total": "总计",
    "Custom": "自定义",
    "Auto": "自动",
    "Always": "始终",
    "Never": "从不",
    "Ran": "已运行",
    "Quick": "快速",
    "Deep": "深度",
    "Context": "上下文",
    "Log Out": "退出登录",
    "Open Folder": "打开文件夹",
    "Browse Marketplace": "浏览插件市场",
    "Suggested": "推荐",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Development": "开发",
    "Early Access": "抢先体验",
    "Nightly": "Nightly",
    "Configured Hooks": "已配置的钩子",
    "Execution Log": "执行日志",
    "Clear log": "清空日志",
    "Tools": "工具",
    "Browser": "浏览器",
    "Installed MCP Servers": "已安装的 MCP 服务器",
    "Off": "关闭",
    "Browser Tab": "浏览器标签页",
    "Copy Command": "复制命令",
    "Checkout": "检出",
    "View Report": "查看报告",
    "Pasted Link": "已粘贴链接",
    "Remote HTTPS": "远程 HTTPS",
    "Command": "命令",
    "Arguments": "参数",
    "Secrets": "密钥",
    "Server URL": "服务器 URL",
    "HTTP headers": "HTTP 请求头",
    "Client ID": "客户端 ID",
    "Client Secret": "客户端密钥",
    "Team Access": "团队访问权限",
    "All Members": "所有成员",
    "Configure": "配置",
    "Remove": "移除",
    "Plugin": "插件",
    "MCP Server": "MCP 服务器",
    "Default Off": "默认关闭",
    "Default On": "默认开启",
    "Required": "必需",
    "Uninstall": "卸载",
    "Add to Team": "添加到团队",
    "Imported": "已导入",
    "Local": "本地",
    "Extension": "扩展",
    "Verified": "已验证",
    "Pinned": "已固定",
    "Previous": "上一个",
    "Next": "下一个",
    "Scopes": "作用域",
    "Options": "选项",
    "Moving...": "正在移动...",
    "Complete": "完成",
    "Failed": "失败",
    "View plan": "查看计划",
    "Mine": "我的",
    "Shared": "共享",
    "Copy Code": "复制代码",
    "Copy link": "复制链接",
    "Open link": "打开链接",
    "Copy table": "复制表格",
    "Zoom in": "放大",
    "Zoom out": "缩小",
    "Show Code": "显示代码",
    "Copy Error": "复制错误",
    "Run History": "运行历史",
    "No Runs Yet": "暂无运行记录",
    "Cancel": "取消",
    "Confirm": "确认",
    "Done": "完成",
    "Hide": "隐藏",
    "Edit": "编辑",
    "Manage": "管理",
    "Save": "保存"
};

module.exports = { safeGlobalDict, riskyShortWords };
